### ISSUE TITLE
Modelagem de Banco de Dados

### ISSUE THREAD

**Issue by Claudia-Nunes** [Dev-s-Domain/Bike4you#1]
Criar o modelo de dados , definindo todos os elementos necessários para criação do site.

**Comment by Jummanso** [comment]
Início modelagem no DBDesigner e estudo Swagger para fazer a documentação da parte do Banco de Dados

**Comment by Lemos05** [comment]
Estudo do Swagger para organização e criação de documentação do Banco de Dados

**Comment by Jummanso** [comment]
Análise da primeira versão do Banco de Dados e preparação de compactação das tabelas do mesmo após análise conjunta com o professor Rodrigo.

[Mapa Banco V.1.pdf](https://github.com/Dev-s-Domain/DomainBicicletas/files/12530406/Mapa.Banco.V.1.pdf)

**Comment by Jummanso** [comment]
Modelagem criada e alterada com P.O..



![Image](https://github.com/Dev-s-Domain/DomainBicicletas/assets/126696706/658c48ec-7415-4cd6-8d97-e489ef352408)
