### ISSUE TITLE
Configuração Inicial do Projeto - Backend

### ISSUE THREAD

**Issue by Claudia-Nunes** [Dev-s-Domain/Bike4you#21]
- [x] Inicialize o projeto Express-NodeJS
- [x] Configure a estrutura de pastas - Padão MVC.
- [x] Configure o sistema de controle de versão (por exemplo, Git).

**Comment by abnercosta97** [comment]
Inicializado configuração inicial do projeto back-end [pagina](https://github.com/Dev-s-Domain/DomainBicicletas/tree/main/back-end)

**Comment by itsmorais** [comment]
Removido arquivo .env do github e adicionado a seguinte linha no arquivo .gitignore:
```
.env
```

**Comment by itsmorais** [comment]
Instalado pacote pg para a utilização do conector do banco de dados postgres
```
npm install pg --save
```
sem essa biblioteca não é possível executar as migrations
![image](https://github.com/Dev-s-Domain/Bike4you/assets/53665466/b778879f-1309-41fd-9c4f-56ee9f39e64e)
